### ISSUE TITLE
按demo集成报Factory method 'connectionSignUp' threw exception; nested exception is java.lang.NullPointerException

### ISSUE THREAD

**Issue by jueding920** [justauth/justauth-spring-boot-security-starter#3]
Error creating bean with name 'connectionSignUp' defined in class path resource [top/dcenter/ums/security/core/oauth/config/Auth2AutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [top.dcenter.ums.security.core.oauth.signup.ConnectionService]: Factory method 'connectionSignUp' threw exception; nested exception is java.lang.NullPointerException

**Comment by ZeroOrInfinity** [comment]
你这个问题可能跟 top.dcenter:justAuth-spring-security-starter:1.1.20  修复的 bug 有关, 更新版本试试. 现在最新版本为 1.1.21.

**Comment by ZeroOrInfinity** [comment]
使用最新版本 1.1.22, 新增一键登录功能. 修复若干 bug, 你的问题应该解决了.
